# Site
title:           'ligne ferroviaire du Lioran'
subtitle:        '150<sup>ième</sup> anniversaire'
short_title:        '150<sup>ième</sup> anniversaire de la ligne ferroviaire du Lioran'
bio:                'Les 150 ans de la ligne ferroviaire du Lioran'
description:        'Les 150 ans de la ligne ferroviaire du Lioran'
locale:             fr_FR
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://150anslignedulioran.fr" # the base hostname & protocol for your site

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/articles/:title/"
    layout: post
    author:

# Jekyll
permalink:          /articles/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus:
  site_id: '150anslignedulioran'

# Social
gtag_manager:       'KKLN36C'
twitter:            default
facebook:           'events/374763476305255'
instagram:          default
github:             default

# personal
location:           '15300 - Le Lioran'
location_link:      'https://goo.gl/maps/4imBQbkRJx32'
phone:              310-318-5555
email:
  contact: 'contact@150anslignedulioran.fr'

map:
  lioran_url: 'https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d11268.794258721273!2d2.7489532!3d45.0817664!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xd86b54b1c2edc19f!2sLe+Lioran!5e0!3m2!1sfr!2sfr!4v1513533462000'

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/articles/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
